---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAKMmORRJ863psQevDUenFJu83nSRvxzxtDY58Zgd3DscAgQ+d3WGkEIGB+u+hrA0ovCG0mkcHR5GipWi4N8mkugUdjOsoCbVQEk3O5tmByveoG0WYetCrqXt5A08JKcC/PDVzpjp3aQbt6XNdgfYAabAk+iW70u9Y2CMzG82/eGMmGS7dQVXqntYgo9qZEM+UTQ41+ZyXKzM84Jnnrk74JTCxXW41P1tkV0M8VLnpnzONVVt1Iki/8fEPm/3scfMvKYsCvRGq47XIj73M4qhIE7e4/qrLgnXCFBF0fdyquNNwM0nuMByMDPhpZ8oTJIyIEotpWiy0VcNNCB4Yyf7QIHU70zHT31jO5WkJ7vJLc5hN8e+mjVDTkJgpdy2dl09Qk3037mRZ1QRd2/4X4PhXBh/gYu/JRxUuGPygZR8dgnRNeBaCCNxgmGyZZKiisQNLFt63mLpoUnXSnoVlGS1TNQsC3J61y3kZxjT0JbPH8j2eZuPlWQVFC0HCGs1lG0x0IrSqdaMQCFROgVad7tBgzgsn3ThAzkp0sVsn+gO6Y/pj/D6Ah198MC1ji4q7joVvpt8ikfi0qhNn9yf3A/6b8OPmGpqb7Hc+CvkscZzAf3441MUro/izXsjvPKb7tek82Mv0piVO92s7fF9g86KQXklKEwgI5ruSX+J6BACTb2CSrSx/xC+5tYrax4Ky06/bILbNxECfZy740mw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
